# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Upper Crust Catering
email: sales@uppercrust-catering.net
description: > # this means to ignore newlines until "baseurl:"
  Whatever the occasion, Chef Mitch Morrell brings 35 years of culinary
  experience to events across Yorkville and the west Chicagoland area.
  Upper Crust offers a wide variety of excellent homemade cuisine
  selections from simple to gourmet, all prepared with Chef Mitch's
  personal touch!

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.uppercrust-catering.net" # the base hostname & protocol for your site

collections:
  menus:
    permalink: /menus/:path/
    output: true

gems:
  - jekyll-redirect-from

full_rebuild: true

# Build settings
markdown: kramdown

prose:
  siteurl: "http://www.uppercrust-catering.net"
  media: "images"
